### ISSUE TITLE
Typescript type definitions incomplete for NodeJS

### ISSUE THREAD

**Issue by jfairley** [FusionAuth/fusionauth-typescript-client#13]
I'm using TypeScript both on the front- and back-end. This library doesn't make it immediately clear that it has front-end dependencies, at least in the types, as is immediately obvious if you install this with a TypeScript Node application.

Please update the Readme, and whatever else necessary to make that more clear.

**Comment by tyduptyler13** [comment]
Hi,

I'm not sure I understand your issue. This client is designed to run in both the browser and the node environment. Could you help me by showing me what we are doing wrong?

-Tyler

**Comment by jfairley** [comment]
@tyduptyler13 Sorry for the slow response. When I install this in my node library, it fails, unable to resolve some browser types like `Request`, `RequestCredentials`, and `FormData`.


```
[node-service-common] tsc                                                                                                                                                                                     
node_modules/@fusionauth/typescript-client/build/src/FusionAuthClient.d.ts:4:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

4     [key: K]: T;
       ~~~

node_modules/@fusionauth/typescript-client/build/src/FusionAuthClient.d.ts:11:18 - error TS2304: Cannot find name 'RequestCredentials'.

11     credentials: RequestCredentials;
                    ~~~~~~~~~~~~~~~~~~

node_modules/@fusionauth/typescript-client/build/src/FusionAuthClient.d.ts:26:34 - error TS2304: Cannot find name 'RequestCredentials'.

26     setRequestCredentials(value: RequestCredentials): FusionAuthClient;
                                    ~~~~~~~~~~~~~~~~~~

node_modules/@fusionauth/typescript-client/build/src/IRESTClient.d.ts:2:53 - error TS2304: Cannot find name 'Response'.

2 export declare type ResponseHandler<T> = (response: Response) => Promise<ClientResponse<T>>;
                                                      ~~~~~~~~

node_modules/@fusionauth/typescript-client/build/src/IRESTClient.d.ts:3:58 - error TS2304: Cannot find name 'Response'.

3 export declare type ErrorResponseHandler<T> = (response: Response) => Promise<ClientResponse<T>>;
                                                           ~~~~~~~~

node_modules/@fusionauth/typescript-client/build/src/IRESTClient.d.ts:21:24 - error TS2304: Cannot find name 'FormData'.

21     withFormData(body: FormData): IRESTClient<RT, ERT>;
                          ~~~~~~~~

node_modules/@fusionauth/typescript-client/build/src/IRESTClient.d.ts:55:28 - error TS2304: Cannot find name 'RequestCredentials'.

55     withCredentials(value: RequestCredentials): IRESTClient<RT, ERT>;
                              ~~~~~~~~~~~~~~~~~~


Found 7 errors.
```


My config is:


```
[node-service-common] tsc --showConfig                                                                                                                                                                        master  ✭
{
    "compilerOptions": {
        "target": "es2016",
        "module": "commonjs",
        "lib": [
            "es7",
            "es2018.asynciterable"
        ],
        "declaration": true,
        "declarationDir": "./dist",
        "outDir": "./dist",
        "rootDir": "./src",
        "strict": true,
        "noImplicitAny": false,
        "strictPropertyInitialization": false,
        "moduleResolution": "node",
        "esModuleInterop": true,
        "inlineSourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "files": [
        "./src/index.ts",
        "./src/amqp/MessageSender.ts",
        "./src/amqp/MessageService.ts",
        "./src/amqp/MessageWorker.ts",
        "./src/amqp/common.ts",
        "./src/amqp/index.ts",
        "./src/auth/FusionAuthWrapper.ts",
        "./src/auth/index.ts",
        "./src/auth/jwt-utils.ts",
        "./src/entities/EntityBase.ts",
        "./src/utilities/db-utils.ts",
        "./src/utilities/logging.ts",
        "./src/utilities/server.ts"
    ],
    "include": [
        "src"
    ],
    "exclude": [
        "node_modules",
        "**/*.test.*"
    ]
}
```

**Comment by jfairley** [comment]
I take it, the issue is that you have `@types/request` listed as a dev dependency, which makes things work for you, but not for me.

You might consider moving `@types/request` to `"dependencies"` _OR_ reworking the code to not rely on `@types/request`.

**Comment by jfairley** [comment]
Well, `@types/request` isn't the issue, so sorry for that suggestion. (I cloned locally, removing that type.)

Either way, it's definitely pulling from TypeScript's `lib.dom.d.ts`. That's where it all falls apart when I'm trying to run it in NodeJS.

<img width="757" alt="Screen Shot 2020-04-21 at 5 03 09 PM" src="https://user-images.githubusercontent.com/992483/79923185-4a4b6200-83f2-11ea-9e06-b057085ebc61.png">

**Comment by tyduptyler13** [comment]
Hi,

Thank you for the notice. I will yank that dependency as well. The problem is likely coming from the `cross-fetch` dependency which determines if we are in the browser or node and polyfills the fetch api if we are in node using request (I think).

Additionally I just refactored this client to hopefully keep all of the REST client stuff separated out of the actual API. See if its still an issue with this refactor.

**Comment by jfairley** [comment]
It seems to be an issue still.

I pulled the latest from `master` then:

```bash
# in fusionauth-typescript-client
npm i
tsc
npm pack

# in my lib
npm i ../fusionauth-typescript-client/fusionauth-typescript-client-1.16.0-RC.2.tgz
tsc
```

This time there are only 6 errors. (It no longer complains about `[key: K]: T;`)

**Comment by tyduptyler13** [comment]
Hi,

So after some investigation it seems that cross-fetch isn't able to provide those types (which it really needs to). Moving forward I think I will have to use a more advanced compilation for browser vs node to get the types right or as a holdover, you will have to include lib.dom.

The workaround for now will be to tell typescript to stop complaining because this is tested on node and it is known to be working, regardless of type information. 

If you have any suggestions moving forward I would be open to them.

**Comment by jfairley** [comment]
Thanks. I'll give that a try. Also if I have any suggestions here, I'll make a pr.

**Comment by tyduptyler13** [comment]
Hi, could you try pulling and testing my types-fix branch and see if it fixes your issue?

**Comment by jfairley** [comment]
@tyduptyler13 I'm using the client, and it builds correctly.

I do have two issues I'm stumped on:

1. My unit tests, which use [`nock`](https://www.npmjs.com/package/nock) fail. It would seem the fusion auth requests changed somehow. I haven't yet dug into details.
2. When I start my app and try login, which uses `exchangeOAuthCodeForAccessToken()` I'm getting the following response:
    * `{"statusCode":400,"exception":{"error":"invalid_request","error_description":"The request is missing a required parameter: grant_type","error_reason":"missing_grant_type"}}`

Did `grant_type` used to be a default parameter in the node client?

---

Another small issue, I see an bunch of fields documented as `(Optional)`, but the TypeScript type should really have a `?:` or a default value ` = ""`. For example, IntelliJ isn't happy with my use of `exchangeRefreshTokenForAccessToken()`, because I'm only giving it 3 params, and TypeScript says I should provide 5.

<img width="936" alt="Screen Shot 2020-05-03 at 8 27 24 AM" src="https://user-images.githubusercontent.com/992483/80916759-f3118f80-8d17-11ea-86ea-7507abbe1b2e.png">

**Comment by tyduptyler13** [comment]
Hi, I believe that this is an issue in all the clients, we don't currently annotate optional parameters in the builder (outside of javadoc), and even then, in some cases the optional parameters don't come first. To solve this in typescript we have been supplying null instead.

**Comment by tyduptyler13** [comment]
As for your other issue, I believe @robotdan is your best source of info.

**Comment by jfairley** [comment]
@tyduptyler13 

Just to update, I've upgraded to the typescript client. I am providing empty-string for those `scope` and `user_code` fields I mentioned in my last comment.

As far as my other issue, it seems to have been fixed at some point, because it's no longer an issue in `1.16.1`.
