### ISSUE TITLE
ObjectMap interface definition error

### ISSUE THREAD

**Issue by cheelahim** [FusionAuth/fusionauth-typescript-client#15]
Client version: 1.15.8

**Problem**
Current definition of the `ObjectMap` interface in `FusionAuthClient.ts`:
```ts
export interface ObjectMap<K extends string | number, T> {
  [key: K]: T
}
```
This leads to the compilation error:
 `TS1023: An index signature parameter type must be either 'string' or 'number'.`

**Possible solutions**

1. Preferably remove the `ObjectMap` interface from the codebase in favor of built-in utility type [Record<K,T>](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkt)

2. Otherwise rewrite the `ObjectMap` as type alias to support union keys:
```ts
export type ObjectMap<K extends string | number, T> = {
  [key in K]: T
}
```

**Comment by robotdan** [comment]
@tyduptyler13 can you take a look ? Is this similar to the issue we just fixed?  https://github.com/FusionAuth/fusionauth-typescript-client/issues/11

**Comment by tyduptyler13** [comment]
Thank you for the input. This was quite helpful in fixing fully typed objects. 👍 I have modified the builder to use Record instead of our ObjectMap which feels cleaner.
