### ISSUE TITLE
ReferenceError: FormData is not defined

### ISSUE THREAD

**Issue by nutellplox** [FusionAuth/fusionauth-typescript-client#16]
I was migrating over from the @fusionauth/node-client and I ended up getting this error `ReferenceError: FormData is not defined` when calling the exchangeOAuthCodeForAccessToken method. 

Am I missing a dependency? I tried to install the FormData npm packge, but that didn't work. I'm kind of new to node, so any help would be greatly appreciated!

**Comment by cheelahim** [comment]
@nutellplox I believe it is a bug in the library. It relies on browser built-in FormData which makes it unusable in the node environment at the moment.

@tyduptyler13 @robotdan I assume this client is supposed to work in both browser and server environments. Is there a specific reason to rely on browser built-in FormData object? The DefaultRESTClient ignores the interface anyway as well as the underlying fetch.
```ts
export default class DefaultRESTClient<RT, ERT> implements IRESTClient<RT, ERT> {
  withFormData(body: object): DefaultRESTClient<RT, ERT> {
    this.body = body;
    this.withHeader('Content-Type', 'application/x-www-form-urlencoded');
    return this;
  }
}

**Comment by tyduptyler13** [comment]
Hi,

This is related to #13. I am still working on a fix that keeps the source separated from both browser and nodejs while still giving the proper type support. I may just end up having two separate REST clients, one for nodejs and one for browser to get the types correct.

The core issue is that we switch to use `cross-fetch` some time back but need more types than what it provides.

**Comment by cheelahim** [comment]
@tyduptyler13 would isomorphic [unfetch](https://github.com/developit/unfetch) with its [isomorphic types](https://github.com/developit/unfetch/blob/master/src/index.d.ts) be a viable alternative?

**Comment by tyduptyler13** [comment]
Hi @cheelahim ,

I have attempted to fix this issue on the fix-types branch. If you would like to try pulling the latest version of that then you shouldn't see any problems.
