### ISSUE TITLE
Build error with generated typings file

### ISSUE THREAD

**Issue by friedemannsommer** [FusionAuth/fusionauth-typescript-client#17]
Typescript Version: `3.8.3`

I'm running into build issues when trying to build an app containing the depency `@fusionauth/typescript-client@1.15.8`.

This is the build error:
```
node_modules/@fusionauth/typescript-client/build/src/FusionAuthClient.d.ts:4:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

4     [key: K]: T;
       ~~~
```

I've tried to find the corresponding line in the sourcecode but i couldn't find an `interface` with the name `ObjectMap`.

**Comment by tyduptyler13** [comment]
This was fixed recently to use `Record` instead. You may have to use our release candidate build instead.

**Comment by friedemannsommer** [comment]
@tyduptyler13 These aren't available on npm, right? I can't find a `@fusionauth/typescript-client` package with `1.16.X`.

**Comment by robotdan** [comment]
I pushed the `1.16.0-RC.1` build if you want to try it. 
https://www.npmjs.com/package/@fusionauth/typescript-client

**Comment by friedemannsommer** [comment]
@robotdan Thanks the build error is gone and the application works :+1:
