### ISSUE TITLE
return 405 when run client.exchangeOAuthCodeForAccessTokenUsingPKCE

### ISSUE THREAD

**Issue by yamatsum** [FusionAuth/fusionauth-typescript-client#45]
I did the following tutorials using fastify.
https://fusionauth.io/docs/v1/tech/5-minute-setup-guide/

The login itself is working fine, but when I run `client.exchangeOAuthCodeForAccessTokenUsingPKCE` I get a 405 error.

There is no problem if it is executed by express as in the sample, but it fails when using fastify. Is there a sample of fastify?

log
```
2021-03-18 4:26:15.120 AM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.oauth2.TokenAction] does not have a valid execute method for the HTTP method [GET]
```

please help

**Comment by jdegger** [comment]
What was the reason you got this?

**Comment by jdegger** [comment]
For anybody having this: It turned out I had written my URL wrong: http://company.fusionauth.io for example instead of `https://`, the redirect to `https://` caused the error

**Comment by mooreds** [comment]
Thanks @jdegger for sharing your experience! I also ported it over to the forum (which gets more traffic, so your advice will help more people). https://fusionauth.io/community/forum/topic/1081/405-when-running-client-exchangeoauthcodeforaccesstokenusingpkce
