### ISSUE TITLE
Provide method to generate the /oauth2/authorize URL

### ISSUE THREAD

**Issue by adriano-di-giovanni** [FusionAuth/fusionauth-typescript-client#49]
I searched through the code but I couldn't find a method that can be invoked to have the `/oauth2/authorize` URL. 

I'm talking about something like Google's [OAuth2Client#generateAuthUrl](https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/oauth2client.ts#L522).

It would be great to have such a method in order to always use the client to send all of the requests.

**Comment by mooreds** [comment]
Thanks for the suggestions @adriano-di-giovanni , appreciate you using FusionAuth and filing this issue!

I filed an [issue here](https://github.com/FusionAuth/fusionauth-issues/issues/1192) as we generate all our client libraries from the same template.

Going to close this out as we can track progress on issue 1192.
