### ISSUE TITLE
ValidateResponse type is wrong

### ISSUE THREAD

**Issue by lamuertepeluda** [FusionAuth/fusionauth-typescript-client#5]
Hi,

[ValidateResponse](https://github.com/FusionAuth/fusionauth-typescript-client/blob/master/src/FusionAuthClient.ts#L5185) returned from validateJWT is wrongly typed. The definition says:

```ts
ValidateResponse.jwt?: Map<string, any>
```

but the response returns a plain object instead. This will make either  the app crash (no methods of Map available) or the compiler complain.

I would suggest rather a different interface definition, e.g.

```ts
// see https://en.wikipedia.org/wiki/JSON_Web_Token#Standard_fields
interface JWT {
  exp: number; // Date expressed as epoch milliseconds as returned by the API
  iat: number;  // Date expressed as epoch milliseconds as returned by the API
  sub: string;
  iss: string;
  aud: string;
  [x: string]: any; // any other option - see https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#strict-object-literal-assignment-checking
}

ValidateResponse.jwt?: JWT
```

**Comment by tyduptyler13** [comment]
The `JWT` java type now maps to `object`

Let me know if this change works.

**Comment by tyduptyler13** [comment]
I'll revisit this when I get the chance so I can add special classes to our java2json tool and add the class/interface described in your post and use that information in any language that supports it.

**Comment by robotdan** [comment]
@lamuertepeluda  can you confirm @tyduptyler13 update has resolved your issue? 
Thanks!!

**Comment by lamuertepeluda** [comment]
@robotdan @tyduptyler13 definitely working! 😃 Thank you!

And sorry for the delay but I was out of office for 2 weeks

**Comment by robotdan** [comment]
Thanks for the update @lamuertepeluda no worries, glad it is working for you!
