### ISSUE TITLE
NPM missing latest version 1.10.2

### ISSUE THREAD

**Issue by ron-johnson** [FusionAuth/fusionauth-typescript-client#7]
We get an error due to a conflict between xhr and another package in our project using version 1.10.0. @tjpeden has submitted the fix to this which has been accepted as version 1.10.2. Any idea when you plan to update NPM with the latest changes? 

We are currently having to compile and link the changes @tjpeden made which is less than desirable as we incorporate fusionauth to the rest of our development team.

**Comment by robotdan** [comment]
Hi @ron-johnson - thanks for taking the time to open the issue. I pushed the release with @tjpeden PR included as `1.10.1`. 

https://www.npmjs.com/package/@fusionauth/typescript-client

Let me know if that works for you!

**Comment by ron-johnson** [comment]
It did, thank you!
